name: Run Shell Script Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make unit-test.sh executable
        run: chmod +x unit-test.sh

      - name: Run unit-test.sh
        run: ./unit-test.sh

